"""Initial migration

Revision ID: 7e834723ff32
Revises:
Create Date: 2025-01-14 15:58:17.035719

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "7e834723ff32"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "comments",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("content", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("file_id", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("user_id", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.ForeignKeyConstraint(
            ["file_id"], ["files.id"], name="comments_file_id_fkey"
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name="comments_user_id_fkey"
        ),
        sa.PrimaryKeyConstraint("id", name="comments_pkey"),
    )
    op.create_index("ix_comments_id", "comments", ["id"], unique=False)
    op.create_table(
        "files",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("filename", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("file_type", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("result_found", sa.BOOLEAN(), autoincrement=False, nullable=True),
        sa.Column("user_id", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], name="files_user_id_fkey"),
        sa.PrimaryKeyConstraint("id", name="files_pkey"),
    )
    op.create_index("ix_files_id", "files", ["id"], unique=False)
    op.create_index("ix_files_filename", "files", ["filename"], unique=False)
    op.create_table(
        "users",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("email", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("password", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.PrimaryKeyConstraint("id", name="users_pkey"),
    )
    op.create_index("ix_users_id", "users", ["id"], unique=False)
    op.create_index("ix_users_email", "users", ["email"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_users_email", table_name="users")
    op.drop_index("ix_users_id", table_name="users")
    op.drop_table("users")
    op.drop_index("ix_files_filename", table_name="files")
    op.drop_index("ix_files_id", table_name="files")
    op.drop_table("files")
    op.drop_index("ix_comments_id", table_name="comments")
    op.drop_table("comments")
    # ### end Alembic commands ###
